# Generated by Django 4.1.3 on 2022-11-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strafbak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512, verbose_name='Reden')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strafbak_giver', to=settings.AUTH_USER_MODEL, verbose_name='Gever')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stafbak_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Ontvanger')),
            ],
            options={
                'verbose_name': 'Strafbak',
                'verbose_name_plural': 'Strafbakken',
            },
        ),
        migrations.CreateModel(
            name='Chug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time', models.TimeField(verbose_name='Tijdstip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Chug',
                'verbose_name_plural': 'Chugs',
            },
        ),
        migrations.CreateModel(
            name='Anytimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512, verbose_name='Reden')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anytimer_giver', to=settings.AUTH_USER_MODEL, verbose_name='Gever')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anytimer_receiver', to=settings.AUTH_USER_MODEL, verbose_name='Ontvanger')),
            ],
            options={
                'verbose_name': 'Anytimer',
                'verbose_name_plural': 'Anytimers',
            },
        ),
    ]
