# Generated by Django 4.1.5 on 2023-01-07 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strafbak',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actief'),
        ),
        migrations.AddField(
            model_name='strafbak',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chug',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='chug',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Tijdstip'),
        ),
        migrations.AlterField(
            model_name='strafbak',
            name='reason',
            field=models.CharField(max_length=512, null=True, verbose_name='Reden'),
        ),
    ]
