# Generated by Django 4.1.3 on 2022-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strafbak',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Getrokken'),
        ),
    ]
