# Generated by Django 4.1.3 on 2022-11-20 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strafbak',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chug',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Datum'),
        ),
    ]
