# Generated by Django 4.1.5 on 2023-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chugs", "0002_strafbak_active_strafbak_date_alter_chug_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strafbak",
            name="date_deleted",
            field=models.DateTimeField(null=True, verbose_name="Datum getrokken"),
        ),
    ]
