# Generated by Django 4.1.3 on 2022-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chugs', '0002_strafbak_date_alter_chug_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strafbak',
            name='reason',
            field=models.CharField(max_length=512, null=True, verbose_name='Reden'),
        ),
    ]
