# Generated by Django 4.1.3 on 2022-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chugs', '0004_alter_chug_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='strafbak',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Actief'),
        ),
    ]
