# Generated by Django 4.1.3 on 2022-11-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Naam')),
                ('price', models.FloatField(verbose_name='Prijs')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producten',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Naam')),
                ('image', models.ImageField(upload_to='product_categories', verbose_name='Afbeelding')),
            ],
            options={
                'verbose_name': 'Productcategorie',
                'verbose_name_plural': 'Productcategorieën',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('description', models.CharField(max_length=512, verbose_name='Omschrijving')),
                ('price', models.FloatField(default=0.0, verbose_name='Prijs')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Transactie',
                'verbose_name_plural': 'Transacties',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AlcoholProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.product')),
                ('alcohol_percentage', models.FloatField(verbose_name='Alcoholpercentage')),
                ('volume', models.FloatField(verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Alcohol-houdend product',
                'verbose_name_plural': 'Alcohol-houdende producten',
            },
            bases=('financial.product',),
        ),
        migrations.CreateModel(
            name='ContributionTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.transaction')),
            ],
            options={
                'verbose_name': 'Contributie',
                'verbose_name_plural': 'Contributies',
            },
            bases=('financial.transaction',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.productcategory', verbose_name='Categorie'),
        ),
    ]
