# Generated by Django 4.1.3 on 2022-11-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.transaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Verkoop',
                'verbose_name_plural': 'Verkopen',
            },
            bases=('financial.transaction',),
        ),
        migrations.CreateModel(
            name='AlcoholSaleTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financial.transaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.alcoholproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Alcohol-verkoop',
                'verbose_name_plural': 'Alcohol-verkopen',
            },
            bases=('financial.transaction',),
        ),
    ]
