# Generated by Django 4.1.3 on 2022-11-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_saletransaction_alcoholsaletransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door'),
        ),
    ]
