# Generated by Django 4.1.3 on 2022-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_alter_foodproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Aantal'),
            preserve_default=False,
        ),
    ]
