# Generated by Django 4.1.5 on 2023-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_transaction_deleted_transaction_settled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholproduct',
            name='alcohol_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alcoholpercentage'),
        ),
        migrations.AlterField(
            model_name='alcoholproduct',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='kcal',
            field=models.IntegerField(verbose_name='Kcal'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='weight',
            field=models.IntegerField(verbose_name='Gewicht (gram)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prijs'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prijs'),
        ),
    ]
