# Generated by Django 4.1.3 on 2022-11-12 15:24

import datetime
from django.db import migrations


def make_initial_users(apps, schema_editor):
    Generation = apps.get_model('users', 'Generation')
    Committee = apps.get_model('users', 'Committee')

    # Generate generations
    g0 = Generation(name='Generatie 0', generation_number=0, start_date='2021-09-01')
    g0.save()

    # Generate committees
    committees = [
        Committee(
            name='Admins',
            abbreviation='admins',
            description='Mensen met oppermacht over IBS',
            created_at=datetime.datetime(2022, 10, 27),
            updated_at=datetime.datetime(2022, 10, 27),
            active=True,
            admin_rights=True,
            website='https://admins.oddinvictus.nl',
            email='admins@oddinvictus.nl',\
            logo='committee_logos/admins.png',
            photo='committee_photos/admins.png'
        ), 
        Committee(
            name='Senaat',
            abbreviation='senaat',
            description='Senaat der O.D.D. Invictus',
            created_at=datetime.datetime(2021, 9, 7),
            updated_at=datetime.datetime(2021, 9, 7),
            active=True,
            admin_rights=True,
            website='https://oddinvictus.nl',
            email='senaat@oddinvictus.nl',
            logo='committee_logos/senaat.jpeg',
            photo='committee_photos/senaat.jpeg',
        ),
        Committee(
            name='Colosseum',
            abbreviation='colosseum',
            description='Inwoners van het Colosseum',
            created_at=datetime.datetime(2022, 1, 2),
            updated_at=datetime.datetime(2022, 1, 2),
            active=True,
            admin_rights=False,
            website='https://colosseum.oddinvictus.nl',
            email='colosseum@oddinvictus.nl',
            logo='committee_logos/colosseum.jpeg',
            photo='committee_photos/colosseum.jpeg',
        ),
        Committee(
            name='Bierco',
            abbreviation='bierco',
            description='Commissie die de speciale borrels regelt.',
            created_at=datetime.datetime(2022, 1, 2),
            updated_at=datetime.datetime(2022, 1, 2),
            active=True,
            admin_rights=False,
            website='https://bierco.oddinvictus.nl',
            email='bierco@oddinvictus.nl',
            logo='committee_logos/bierco.jpeg',
            photo='committee_photos/bierco.jpeg',
        ),
        Committee(
            name='De Bakkentrekkers',
            abbreviation='ict',
            description='De mensen die de ICT van Invictus regelen.',
            created_at=datetime.datetime(2022, 10, 27),
            updated_at=datetime.datetime(2021, 10, 27),
            active=True,
            admin_rights=False,
            website='https://bakkentrekkers.oddinvictus.nl',
            email='bakkentrekkers@oddinvictus.nl',
            logo='committee_logos/bakkentrekkers.jpeg',
            photo='committee_photos/bakkentrekkers.jpeg',
        ),
        Committee(
            name='Kas Commissie',
            abbreviation='kasco',
            description='Extra penningmeesters, leuk!',
            created_at=datetime.datetime(2022, 10, 27),
            updated_at=datetime.datetime(2022, 10, 27),
            active=True,
            admin_rights=False,
            website='https://kasco.oddinvictus.nl',
            email='kasco@oddinvictus.nl',
            logo='committee_logos/kasco.jpeg',
            photo='committee_photos/kasco.jpeg',
        ),
        Committee(
            name='Feuten Pest Commissie',
            abbreviation='fepeco',
            description='Iemand moet de feuten pesten, deze mensen doen dat.',
            created_at=datetime.datetime(2022, 10, 27),
            updated_at=datetime.datetime(2022, 10, 27),
            active=True,
            admin_rights=False,
            website='https://fepeco.oddinvictus.nl',
            email='fepeco@oddinvictus.nl',
            logo='committee_logos/fepeco.jpeg',
            photo='committee_photos/fepeco.jpeg',
        ),
        Committee(
            name='Invictus Vakantie Commissie',
            abbreviation='invakancie',
            description='De mensen die de vakanties van Invictus regelen.',
            created_at=datetime.datetime(2022, 1, 2),
            updated_at=datetime.datetime(2022, 1, 2),
            active=True,
            admin_rights=False,
            website='https://invakancie.oddinvictus.nl',
            email='invakancie@oddinvictus.nl',
            logo='committee_logos/invakancie.jpeg',
            photo='committee_photos/invakancie.jpeg',
        ),
    ]

    for committee in committees:
        committee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_initial_users),
    ]
