# Generated by Django 4.1.5 on 2023-01-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230111_2146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Laatst gesynchroniseerd'),
        ),
    ]
