# Generated by Django 4.1.3 on 2022-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_bierco_remove_user_is_colosseum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='begin',
            field=models.DateField(auto_now_add=True, verbose_name='Begonnen op'),
        ),
    ]
