# Generated by Django 4.1.3 on 2022-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_function_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/committee_logos', verbose_name='Commissie logo'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/committee_photos', verbose_name='Commissie foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile_pictures'),
        ),
    ]
