# Generated by Django 4.1.3 on 2022-11-12 15:24

import datetime
from django.db import migrations


def make_initial_users(apps, schema_editor):
    Committee = apps.get_model('users', 'Committee')

    # Generate committees
    committees = [
        Committee(
            name='Members',
            abbreviation='members',
            description='Voor de leden!',
            created_at=datetime.datetime(2021, 9, 7),
            updated_at=datetime.datetime(2021, 9, 7),
            active=True,
            admin_rights=True,
            website='https://leden.oddinvictus.nl',
            email='leden@oddinvictus.nl',\
            logo='committee_logos/leden.png',
            photo='committee_photos/leden.png'
        ),
        Committee(
            name='Aspiring Members',
            abbreviation='aspiring',
            description='Bah, feuten!',
            created_at=datetime.datetime(2021, 9, 7),
            updated_at=datetime.datetime(2021, 9, 7),
            active=True,
            admin_rights=True,
            website='https://feuten.oddinvictus.nl',
            email='feuten@oddinvictus.nl',\
            logo='committee_logos/feuten.png',
            photo='committee_photos/feuten.png'
        )
    ]

    for committee in committees:
        committee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_committee_logo_alter_committee_photo_and_more'),
    ]

    operations = [
        migrations.RunPython(make_initial_users),
    ]
