# Generated by Django 4.1.3 on 2022-11-13 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='became_aspiring_member',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 15, 45, 40, 887229), verbose_name='Datum van aspirant-lidmaatschap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mailadres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_drink_invited_at',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 15, 45, 47, 964350), verbose_name='Datum van eerste meeborrel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Gebruikersnaam'),
        ),
    ]
