# Generated by Django 4.1.3 on 2022-11-21 16:33

from django.db import migrations
from django.conf import settings


def make_ibs_user(apps, schema_editor):
    IbsUser = apps.get_model('users', 'User')
    Generartion = apps.get_model('users', 'Generation')
    # from django.contrib.auth.models import User

    gen = Generartion.objects.get(generation_number=0)
    username = settings.DEFAULT_IBS_USER_USERNAME
    email = settings.DEFAULT_IBS_USER_EMAIL

    user = IbsUser.objects.create_user(
        username, 
        email,
        first_name='Invictus',
        last_name='Bier Systeem',
        birth_date='2021-09-07',
        first_drink_invited_at='2021-09-07',
        became_aspiring_member='2021-09-07',
        generation=gen,
        bio='Account voor automagische IBS dingetjes',
        phone_number='0612345678',
    )

    user.active = False

    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_became_aspiring_member_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RunPython(make_ibs_user),
    ]
