# Generated by Django 4.1.3 on 2022-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221121_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Function',
            new_name='CommitteeMember',
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['end', '-begin', 'user'], 'verbose_name': 'Committee Member', 'verbose_name_plural': 'Committee Members'},
        ),
        migrations.AlterField(
            model_name='generation',
            name='generation_number',
            field=models.IntegerField(unique=True, verbose_name='Generatie nummer'),
        ),
    ]
