# Generated by Django 4.1.3 on 2022-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_function_committeemember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='became_aspiring_member',
            field=models.DateField(blank=True, null=True, verbose_name='Datum van aspirant-lidmaatschap'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_drink_invited_at',
            field=models.DateField(blank=True, null=True, verbose_name='Datum van eerste meeborrel'),
        ),
    ]
