# Generated by Django 4.1.4 on 2023-01-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_became_aspiring_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['name'], 'verbose_name': 'Commissie', 'verbose_name_plural': 'Commissies'},
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['end', '-begin', 'user'], 'verbose_name': 'Commissie lid', 'verbose_name_plural': 'Commissie leden'},
        ),
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['generation_number'], 'verbose_name': 'Generatie', 'verbose_name_plural': 'Generaties'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Gebruiker', 'verbose_name_plural': 'Gebruikers'},
        ),
    ]
