# Generated by Django 4.1.5 on 2023-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_became_aspiring_member_and_more'),
        ('users', '0012_alter_committee_options_and_more'),
    ]

    operations = [
    ]
