# Generated by Django 4.1.3 on 2022-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('organisation', models.IntegerField()),
                ('people', models.CharField(max_length=10000)),
            ],
        ),
    ]
