# Generated by Django 4.1.3 on 2022-11-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='organisation',
        ),
        migrations.AddField(
            model_name='activity',
            name='organisation_id',
            field=models.IntegerField(default=0, verbose_name='Organisatie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='people',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Aanwezigen'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(verbose_name='Starttijd'),
        ),
    ]
