# Generated by Django 4.1.3 on 2022-11-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activity_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePresent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.IntegerField(verbose_name='Activiteit')),
                ('person_id', models.IntegerField(verbose_name='Persoon')),
                ('present', models.BooleanField(verbose_name='Aanwezig')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='people',
        ),
    ]
