# Generated by Django 4.1.3 on 2022-11-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activity_organisation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='person',
            new_name='user',
        ),
    ]
