# Generated by Django 4.1.4 on 2023-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_options_activity_members_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Deelnemer', 'verbose_name_plural': 'Deelnemers'},
        ),
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
