#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A ibs inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

pipenv shell

celery -A ibs  \
    --broker="${CELERY_BROKER}" \
    flower